/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyDetectControlnetDetectPost
 */
export interface BodyDetectControlnetDetectPost {
    /**
     * 
     * @type {string}
     * @memberof BodyDetectControlnetDetectPost
     */
    controlnetModule?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BodyDetectControlnetDetectPost
     */
    controlnetInputImages?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof BodyDetectControlnetDetectPost
     */
    controlnetProcessorRes?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyDetectControlnetDetectPost
     */
    controlnetThresholdA?: number;
    /**
     * 
     * @type {number}
     * @memberof BodyDetectControlnetDetectPost
     */
    controlnetThresholdB?: number;
}

/**
 * Check if a given object implements the BodyDetectControlnetDetectPost interface.
 */
export function instanceOfBodyDetectControlnetDetectPost(value: object): value is BodyDetectControlnetDetectPost {
    return true;
}

export function BodyDetectControlnetDetectPostFromJSON(json: any): BodyDetectControlnetDetectPost {
    return BodyDetectControlnetDetectPostFromJSONTyped(json, false);
}

export function BodyDetectControlnetDetectPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyDetectControlnetDetectPost {
    if (json == null) {
        return json;
    }
    return {
        
        'controlnetModule': json['controlnet_module'] == null ? undefined : json['controlnet_module'],
        'controlnetInputImages': json['controlnet_input_images'] == null ? undefined : json['controlnet_input_images'],
        'controlnetProcessorRes': json['controlnet_processor_res'] == null ? undefined : json['controlnet_processor_res'],
        'controlnetThresholdA': json['controlnet_threshold_a'] == null ? undefined : json['controlnet_threshold_a'],
        'controlnetThresholdB': json['controlnet_threshold_b'] == null ? undefined : json['controlnet_threshold_b'],
    };
}

export function BodyDetectControlnetDetectPostToJSON(json: any): BodyDetectControlnetDetectPost {
    return BodyDetectControlnetDetectPostToJSONTyped(json, false);
}

export function BodyDetectControlnetDetectPostToJSONTyped(value?: BodyDetectControlnetDetectPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'controlnet_module': value['controlnetModule'],
        'controlnet_input_images': value['controlnetInputImages'],
        'controlnet_processor_res': value['controlnetProcessorRes'],
        'controlnet_threshold_a': value['controlnetThresholdA'],
        'controlnet_threshold_b': value['controlnetThresholdB'],
    };
}

