/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyViewControlnetFastloadViewPost
 */
export interface BodyViewControlnetFastloadViewPost {
    /**
     * 
     * @type {string}
     * @memberof BodyViewControlnetFastloadViewPost
     */
    filepath?: string;
    /**
     * 
     * @type {string}
     * @memberof BodyViewControlnetFastloadViewPost
     */
    exceptType?: string;
}

/**
 * Check if a given object implements the BodyViewControlnetFastloadViewPost interface.
 */
export function instanceOfBodyViewControlnetFastloadViewPost(value: object): value is BodyViewControlnetFastloadViewPost {
    return true;
}

export function BodyViewControlnetFastloadViewPostFromJSON(json: any): BodyViewControlnetFastloadViewPost {
    return BodyViewControlnetFastloadViewPostFromJSONTyped(json, false);
}

export function BodyViewControlnetFastloadViewPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyViewControlnetFastloadViewPost {
    if (json == null) {
        return json;
    }
    return {
        
        'filepath': json['filepath'] == null ? undefined : json['filepath'],
        'exceptType': json['except_type'] == null ? undefined : json['except_type'],
    };
}

  export function BodyViewControlnetFastloadViewPostToJSON(json: any): BodyViewControlnetFastloadViewPost {
      return BodyViewControlnetFastloadViewPostToJSONTyped(json, false);
  }

  export function BodyViewControlnetFastloadViewPostToJSONTyped(value?: BodyViewControlnetFastloadViewPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filepath': value['filepath'],
        'except_type': value['exceptType'],
    };
}

