/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyDeoldifyImageDeoldifyImagePost
 */
export interface BodyDeoldifyImageDeoldifyImagePost {
    /**
     * 
     * @type {string}
     * @memberof BodyDeoldifyImageDeoldifyImagePost
     */
    inputImage?: string;
    /**
     * 
     * @type {number}
     * @memberof BodyDeoldifyImageDeoldifyImagePost
     */
    renderFactor?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BodyDeoldifyImageDeoldifyImagePost
     */
    artistic?: boolean;
}

/**
 * Check if a given object implements the BodyDeoldifyImageDeoldifyImagePost interface.
 */
export function instanceOfBodyDeoldifyImageDeoldifyImagePost(value: object): value is BodyDeoldifyImageDeoldifyImagePost {
    return true;
}

export function BodyDeoldifyImageDeoldifyImagePostFromJSON(json: any): BodyDeoldifyImageDeoldifyImagePost {
    return BodyDeoldifyImageDeoldifyImagePostFromJSONTyped(json, false);
}

export function BodyDeoldifyImageDeoldifyImagePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyDeoldifyImageDeoldifyImagePost {
    if (json == null) {
        return json;
    }
    return {
        
        'inputImage': json['input_image'] == null ? undefined : json['input_image'],
        'renderFactor': json['render_factor'] == null ? undefined : json['render_factor'],
        'artistic': json['artistic'] == null ? undefined : json['artistic'],
    };
}

export function BodyDeoldifyImageDeoldifyImagePostToJSON(json: any): BodyDeoldifyImageDeoldifyImagePost {
    return BodyDeoldifyImageDeoldifyImagePostToJSONTyped(json, false);
}

export function BodyDeoldifyImageDeoldifyImagePostToJSONTyped(value?: BodyDeoldifyImageDeoldifyImagePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'input_image': value['inputImage'],
        'render_factor': value['renderFactor'],
        'artistic': value['artistic'],
    };
}

