/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyFetchControlnetFastloadFetchPost
 */
export interface BodyFetchControlnetFastloadFetchPost {
    /**
     * 
     * @type {string}
     * @memberof BodyFetchControlnetFastloadFetchPost
     */
    returnFileType?: string;
    /**
     * 
     * @type {string}
     * @memberof BodyFetchControlnetFastloadFetchPost
     */
    extraPicBase64?: string;
    /**
     * 
     * @type {number}
     * @memberof BodyFetchControlnetFastloadFetchPost
     */
    controlNetID: number;
}

/**
 * Check if a given object implements the BodyFetchControlnetFastloadFetchPost interface.
 */
export function instanceOfBodyFetchControlnetFastloadFetchPost(value: object): value is BodyFetchControlnetFastloadFetchPost {
    if (!('controlNetID' in value) || value['controlNetID'] === undefined) return false;
    return true;
}

export function BodyFetchControlnetFastloadFetchPostFromJSON(json: any): BodyFetchControlnetFastloadFetchPost {
    return BodyFetchControlnetFastloadFetchPostFromJSONTyped(json, false);
}

export function BodyFetchControlnetFastloadFetchPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyFetchControlnetFastloadFetchPost {
    if (json == null) {
        return json;
    }
    return {
        
        'returnFileType': json['returnFileType'] == null ? undefined : json['returnFileType'],
        'extraPicBase64': json['extraPicBase64'] == null ? undefined : json['extraPicBase64'],
        'controlNetID': json['ControlNetID'],
    };
}

  export function BodyFetchControlnetFastloadFetchPostToJSON(json: any): BodyFetchControlnetFastloadFetchPost {
      return BodyFetchControlnetFastloadFetchPostToJSONTyped(json, false);
  }

  export function BodyFetchControlnetFastloadFetchPostToJSONTyped(value?: BodyFetchControlnetFastloadFetchPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'returnFileType': value['returnFileType'],
        'extraPicBase64': value['extraPicBase64'],
        'ControlNetID': value['controlNetID'],
    };
}

