/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateResponse
 */
export interface CreateResponse {
    /**
     * Response string from create embedding or hypernetwork task.
     * @type {string}
     * @memberof CreateResponse
     */
    info: string;
}

/**
 * Check if a given object implements the CreateResponse interface.
 */
export function instanceOfCreateResponse(value: object): value is CreateResponse {
    if (!('info' in value) || value['info'] === undefined) return false;
    return true;
}

export function CreateResponseFromJSON(json: any): CreateResponse {
    return CreateResponseFromJSONTyped(json, false);
}

export function CreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'info': json['info'],
    };
}

export function CreateResponseToJSON(json: any): CreateResponse {
    return CreateResponseToJSONTyped(json, false);
}

export function CreateResponseToJSONTyped(value?: CreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'info': value['info'],
    };
}

