/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmbeddingItem
 */
export interface EmbeddingItem {
    /**
     * The number of steps that were used to train this embedding, if available
     * @type {number}
     * @memberof EmbeddingItem
     */
    step?: number;
    /**
     * The hash of the checkpoint this embedding was trained on, if available
     * @type {string}
     * @memberof EmbeddingItem
     */
    sdCheckpoint?: string;
    /**
     * The name of the checkpoint this embedding was trained on, if available. Note that this is the name that was used by the trainer; for a stable identifier, use `sd_checkpoint` instead
     * @type {string}
     * @memberof EmbeddingItem
     */
    sdCheckpointName?: string;
    /**
     * The length of each individual vector in the embedding
     * @type {number}
     * @memberof EmbeddingItem
     */
    shape: number;
    /**
     * The number of vectors in the embedding
     * @type {number}
     * @memberof EmbeddingItem
     */
    vectors: number;
}

/**
 * Check if a given object implements the EmbeddingItem interface.
 */
export function instanceOfEmbeddingItem(value: object): value is EmbeddingItem {
    if (!('shape' in value) || value['shape'] === undefined) return false;
    if (!('vectors' in value) || value['vectors'] === undefined) return false;
    return true;
}

export function EmbeddingItemFromJSON(json: any): EmbeddingItem {
    return EmbeddingItemFromJSONTyped(json, false);
}

export function EmbeddingItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingItem {
    if (json == null) {
        return json;
    }
    return {
        
        'step': json['step'] == null ? undefined : json['step'],
        'sdCheckpoint': json['sd_checkpoint'] == null ? undefined : json['sd_checkpoint'],
        'sdCheckpointName': json['sd_checkpoint_name'] == null ? undefined : json['sd_checkpoint_name'],
        'shape': json['shape'],
        'vectors': json['vectors'],
    };
}

  export function EmbeddingItemToJSON(json: any): EmbeddingItem {
      return EmbeddingItemToJSONTyped(json, false);
  }

  export function EmbeddingItemToJSONTyped(value?: EmbeddingItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'step': value['step'],
        'sd_checkpoint': value['sdCheckpoint'],
        'sd_checkpoint_name': value['sdCheckpointName'],
        'shape': value['shape'],
        'vectors': value['vectors'],
    };
}

