/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmbeddingItem } from './EmbeddingItem';
import {
    EmbeddingItemFromJSON,
    EmbeddingItemFromJSONTyped,
    EmbeddingItemToJSON,
    EmbeddingItemToJSONTyped,
} from './EmbeddingItem';

/**
 * 
 * @export
 * @interface EmbeddingsResponse
 */
export interface EmbeddingsResponse {
    /**
     * Embeddings loaded for the current model
     * @type {{ [key: string]: EmbeddingItem; }}
     * @memberof EmbeddingsResponse
     */
    loaded: { [key: string]: EmbeddingItem; };
    /**
     * Embeddings skipped for the current model (likely due to architecture incompatibility)
     * @type {{ [key: string]: EmbeddingItem; }}
     * @memberof EmbeddingsResponse
     */
    skipped: { [key: string]: EmbeddingItem; };
}

/**
 * Check if a given object implements the EmbeddingsResponse interface.
 */
export function instanceOfEmbeddingsResponse(value: object): value is EmbeddingsResponse {
    if (!('loaded' in value) || value['loaded'] === undefined) return false;
    if (!('skipped' in value) || value['skipped'] === undefined) return false;
    return true;
}

export function EmbeddingsResponseFromJSON(json: any): EmbeddingsResponse {
    return EmbeddingsResponseFromJSONTyped(json, false);
}

export function EmbeddingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'loaded': (mapValues(json['loaded'], EmbeddingItemFromJSON)),
        'skipped': (mapValues(json['skipped'], EmbeddingItemFromJSON)),
    };
}

  export function EmbeddingsResponseToJSON(json: any): EmbeddingsResponse {
      return EmbeddingsResponseToJSONTyped(json, false);
  }

  export function EmbeddingsResponseToJSONTyped(value?: EmbeddingsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'loaded': (mapValues(value['loaded'], EmbeddingItemToJSON)),
        'skipped': (mapValues(value['skipped'], EmbeddingItemToJSON)),
    };
}

