/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtrasSingleImageResponse
 */
export interface ExtrasSingleImageResponse {
    /**
     * A series of HTML tags containing the process info.
     * @type {string}
     * @memberof ExtrasSingleImageResponse
     */
    htmlInfo: string;
    /**
     * The generated image in base64 format.
     * @type {string}
     * @memberof ExtrasSingleImageResponse
     */
    image?: string;
}

/**
 * Check if a given object implements the ExtrasSingleImageResponse interface.
 */
export function instanceOfExtrasSingleImageResponse(value: object): value is ExtrasSingleImageResponse {
    if (!('htmlInfo' in value) || value['htmlInfo'] === undefined) return false;
    return true;
}

export function ExtrasSingleImageResponseFromJSON(json: any): ExtrasSingleImageResponse {
    return ExtrasSingleImageResponseFromJSONTyped(json, false);
}

export function ExtrasSingleImageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtrasSingleImageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'htmlInfo': json['html_info'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

  export function ExtrasSingleImageResponseToJSON(json: any): ExtrasSingleImageResponse {
      return ExtrasSingleImageResponseToJSONTyped(json, false);
  }

  export function ExtrasSingleImageResponseToJSONTyped(value?: ExtrasSingleImageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'html_info': value['htmlInfo'],
        'image': value['image'],
    };
}

