/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtrasBatchImagesResponse
 */
export interface ExtrasBatchImagesResponse {
    /**
     * A series of HTML tags containing the process info.
     * @type {string}
     * @memberof ExtrasBatchImagesResponse
     */
    htmlInfo: string;
    /**
     * The generated images in base64 format.
     * @type {Array<string>}
     * @memberof ExtrasBatchImagesResponse
     */
    images: Array<string>;
}

/**
 * Check if a given object implements the ExtrasBatchImagesResponse interface.
 */
export function instanceOfExtrasBatchImagesResponse(value: object): value is ExtrasBatchImagesResponse {
    if (!('htmlInfo' in value) || value['htmlInfo'] === undefined) return false;
    if (!('images' in value) || value['images'] === undefined) return false;
    return true;
}

export function ExtrasBatchImagesResponseFromJSON(json: any): ExtrasBatchImagesResponse {
    return ExtrasBatchImagesResponseFromJSONTyped(json, false);
}

export function ExtrasBatchImagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtrasBatchImagesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'htmlInfo': json['html_info'],
        'images': json['images'],
    };
}

  export function ExtrasBatchImagesResponseToJSON(json: any): ExtrasBatchImagesResponse {
      return ExtrasBatchImagesResponseToJSONTyped(json, false);
  }

  export function ExtrasBatchImagesResponseToJSONTyped(value?: ExtrasBatchImagesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'html_info': value['htmlInfo'],
        'images': value['images'],
    };
}

