/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileData
 */
export interface FileData {
    /**
     * Base64 representation of the file
     * @type {string}
     * @memberof FileData
     */
    data: string;
    /**
     * 
     * @type {string}
     * @memberof FileData
     */
    name: string;
}

/**
 * Check if a given object implements the FileData interface.
 */
export function instanceOfFileData(value: object): value is FileData {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FileDataFromJSON(json: any): FileData {
    return FileDataFromJSONTyped(json, false);
}

export function FileDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileData {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'name': json['name'],
    };
}

  export function FileDataToJSON(json: any): FileData {
      return FileDataToJSONTyped(json, false);
  }

  export function FileDataToJSONTyped(value?: FileData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'name': value['name'],
    };
}

