/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageToImageResponse
 */
export interface ImageToImageResponse {
    /**
     * The generated image in base64 format.
     * @type {Array<string>}
     * @memberof ImageToImageResponse
     */
    images?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof ImageToImageResponse
     */
    parameters: object;
    /**
     * 
     * @type {string}
     * @memberof ImageToImageResponse
     */
    info: string;
}

/**
 * Check if a given object implements the ImageToImageResponse interface.
 */
export function instanceOfImageToImageResponse(value: object): value is ImageToImageResponse {
    if (!('parameters' in value) || value['parameters'] === undefined) return false;
    if (!('info' in value) || value['info'] === undefined) return false;
    return true;
}

export function ImageToImageResponseFromJSON(json: any): ImageToImageResponse {
    return ImageToImageResponseFromJSONTyped(json, false);
}

export function ImageToImageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageToImageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'images': json['images'] == null ? undefined : json['images'],
        'parameters': json['parameters'],
        'info': json['info'],
    };
}

  export function ImageToImageResponseToJSON(json: any): ImageToImageResponse {
      return ImageToImageResponseToJSONTyped(json, false);
  }

  export function ImageToImageResponseToJSONTyped(value?: ImageToImageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'images': value['images'],
        'parameters': value['parameters'],
        'info': value['info'],
    };
}

