/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InterrogateRequest
 */
export interface InterrogateRequest {
    /**
     * Image to work on, must be a Base64 string containing the image's data.
     * @type {string}
     * @memberof InterrogateRequest
     */
    image?: string;
    /**
     * The interrogate model used.
     * @type {string}
     * @memberof InterrogateRequest
     */
    model?: string;
}

/**
 * Check if a given object implements the InterrogateRequest interface.
 */
export function instanceOfInterrogateRequest(value: object): value is InterrogateRequest {
    return true;
}

export function InterrogateRequestFromJSON(json: any): InterrogateRequest {
    return InterrogateRequestFromJSONTyped(json, false);
}

export function InterrogateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterrogateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'] == null ? undefined : json['image'],
        'model': json['model'] == null ? undefined : json['model'],
    };
}

  export function InterrogateRequestToJSON(json: any): InterrogateRequest {
      return InterrogateRequestToJSONTyped(json, false);
  }

  export function InterrogateRequestToJSONTyped(value?: InterrogateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
        'model': value['model'],
    };
}

