/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LatentUpscalerModeItem
 */
export interface LatentUpscalerModeItem {
    /**
     * 
     * @type {string}
     * @memberof LatentUpscalerModeItem
     */
    name: string;
}

/**
 * Check if a given object implements the LatentUpscalerModeItem interface.
 */
export function instanceOfLatentUpscalerModeItem(value: object): value is LatentUpscalerModeItem {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function LatentUpscalerModeItemFromJSON(json: any): LatentUpscalerModeItem {
    return LatentUpscalerModeItemFromJSONTyped(json, false);
}

export function LatentUpscalerModeItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): LatentUpscalerModeItem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

  export function LatentUpscalerModeItemToJSON(json: any): LatentUpscalerModeItem {
      return LatentUpscalerModeItemToJSONTyped(json, false);
  }

  export function LatentUpscalerModeItemToJSONTyped(value?: LatentUpscalerModeItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

