/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoraApiJSON
 */
export interface LoraApiJSON {
    /**
     * 
     * @type {string}
     * @memberof LoraApiJSON
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LoraApiJSON
     */
    alias: string;
    /**
     * 
     * @type {string}
     * @memberof LoraApiJSON
     */
    path?: string;
    /**
     * 
     * @type {object}
     * @memberof LoraApiJSON
     */
    metadata?: object;
}

/**
 * Check if a given object implements the LoraApiJSON interface.
 */
export function instanceOfLoraApiJSON(value: object): value is LoraApiJSON {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('alias' in value) || value['alias'] === undefined) return false;
    return true;
}

export function LoraApiJSONFromJSON(json: any): LoraApiJSON {
    return LoraApiJSONFromJSONTyped(json, false);
}

export function LoraApiJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoraApiJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'alias': json['alias'],
        'path': json['path'] == null ? undefined : json['path'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function LoraApiJSONToJSON(json: any): LoraApiJSON {
    return LoraApiJSONToJSONTyped(json, false);
}

export function LoraApiJSONToJSONTyped(value?: LoraApiJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'alias': value['alias'],
        'path': value['path'],
        'metadata': value['metadata'],
    };
}

