/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreprocessResponse
 */
export interface PreprocessResponse {
    /**
     * Response string from preprocessing task.
     * @type {string}
     * @memberof PreprocessResponse
     */
    info: string;
}

/**
 * Check if a given object implements the PreprocessResponse interface.
 */
export function instanceOfPreprocessResponse(value: object): value is PreprocessResponse {
    if (!('info' in value) || value['info'] === undefined) return false;
    return true;
}

export function PreprocessResponseFromJSON(json: any): PreprocessResponse {
    return PreprocessResponseFromJSONTyped(json, false);
}

export function PreprocessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreprocessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'info': json['info'],
    };
}

  export function PreprocessResponseToJSON(json: any): PreprocessResponse {
      return PreprocessResponseToJSONTyped(json, false);
  }

  export function PreprocessResponseToJSONTyped(value?: PreprocessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'info': value['info'],
    };
}

