/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuicksettingsHint
 */
export interface QuicksettingsHint {
    /**
     * 
     * @type {string}
     * @memberof QuicksettingsHint
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof QuicksettingsHint
     */
    label: string;
}

/**
 * Check if a given object implements the QuicksettingsHint interface.
 */
export function instanceOfQuicksettingsHint(value: object): value is QuicksettingsHint {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function QuicksettingsHintFromJSON(json: any): QuicksettingsHint {
    return QuicksettingsHintFromJSONTyped(json, false);
}

export function QuicksettingsHintFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuicksettingsHint {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'label': json['label'],
    };
}

export function QuicksettingsHintToJSON(json: any): QuicksettingsHint {
    return QuicksettingsHintToJSONTyped(json, false);
}

export function QuicksettingsHintToJSONTyped(value?: QuicksettingsHint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'label': value['label'],
    };
}

