/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RealesrganItem
 */
export interface RealesrganItem {
    /**
     * 
     * @type {string}
     * @memberof RealesrganItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RealesrganItem
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof RealesrganItem
     */
    scale?: number;
}

/**
 * Check if a given object implements the RealesrganItem interface.
 */
export function instanceOfRealesrganItem(value: object): value is RealesrganItem {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RealesrganItemFromJSON(json: any): RealesrganItem {
    return RealesrganItemFromJSONTyped(json, false);
}

export function RealesrganItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RealesrganItem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'path': json['path'] == null ? undefined : json['path'],
        'scale': json['scale'] == null ? undefined : json['scale'],
    };
}

  export function RealesrganItemToJSON(json: any): RealesrganItem {
      return RealesrganItemToJSONTyped(json, false);
  }

  export function RealesrganItemToJSONTyped(value?: RealesrganItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'path': value['path'],
        'scale': value['scale'],
    };
}

