/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Request
 */
export interface Request {
}

/**
 * Check if a given object implements the Request interface.
 */
export function instanceOfRequest(value: object): value is Request {
    return true;
}

export function RequestFromJSON(json: any): Request {
    return RequestFromJSONTyped(json, false);
}

export function RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Request {
    return json;
}

  export function RequestToJSON(json: any): Request {
      return RequestToJSONTyped(json, false);
  }

  export function RequestToJSONTyped(value?: Request | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

