/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SDModelItem
 */
export interface SDModelItem {
    /**
     * 
     * @type {string}
     * @memberof SDModelItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SDModelItem
     */
    modelName: string;
    /**
     * 
     * @type {string}
     * @memberof SDModelItem
     */
    hash?: string;
    /**
     * 
     * @type {string}
     * @memberof SDModelItem
     */
    sha256?: string;
    /**
     * 
     * @type {string}
     * @memberof SDModelItem
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof SDModelItem
     */
    config?: string;
}

/**
 * Check if a given object implements the SDModelItem interface.
 */
export function instanceOfSDModelItem(value: object): value is SDModelItem {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('modelName' in value) || value['modelName'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    return true;
}

export function SDModelItemFromJSON(json: any): SDModelItem {
    return SDModelItemFromJSONTyped(json, false);
}

export function SDModelItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SDModelItem {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'modelName': json['model_name'],
        'hash': json['hash'] == null ? undefined : json['hash'],
        'sha256': json['sha256'] == null ? undefined : json['sha256'],
        'filename': json['filename'],
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function SDModelItemToJSON(json: any): SDModelItem {
    return SDModelItemToJSONTyped(json, false);
}

export function SDModelItemToJSONTyped(value?: SDModelItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'model_name': value['modelName'],
        'hash': value['hash'],
        'sha256': value['sha256'],
        'filename': value['filename'],
        'config': value['config'],
    };
}

