/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StableDiffusionProcessingImg2Img
 */
export interface StableDiffusionProcessingImg2Img {
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingImg2Img
     */
    prompt?: string;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingImg2Img
     */
    negativePrompt?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StableDiffusionProcessingImg2Img
     */
    styles?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    seed?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    subseed?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    subseedStrength?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    seedResizeFromH?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    seedResizeFromW?: number;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingImg2Img
     */
    samplerName?: string;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    batchSize?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    nIter?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    steps?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    cfgScale?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    height?: number;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingImg2Img
     */
    restoreFaces?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingImg2Img
     */
    tiling?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingImg2Img
     */
    doNotSaveSamples?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingImg2Img
     */
    doNotSaveGrid?: boolean;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    eta?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    denoisingStrength?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    sMinUncond?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    sChurn?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    sTmax?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    sTmin?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    sNoise?: number;
    /**
     * 
     * @type {object}
     * @memberof StableDiffusionProcessingImg2Img
     */
    overrideSettings?: object;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingImg2Img
     */
    overrideSettingsRestoreAfterwards?: boolean;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingImg2Img
     */
    refinerCheckpoint?: string;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    refinerSwitchAt?: number;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingImg2Img
     */
    disableExtraNetworks?: boolean;
    /**
     * 
     * @type {object}
     * @memberof StableDiffusionProcessingImg2Img
     */
    comments?: object;
    /**
     * 
     * @type {Array<any>}
     * @memberof StableDiffusionProcessingImg2Img
     */
    initImages?: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    resizeMode?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    imageCfgScale?: number;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingImg2Img
     */
    mask?: string;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    maskBlurX?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    maskBlurY?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    maskBlur?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    inpaintingFill?: number;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingImg2Img
     */
    inpaintFullRes?: boolean;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    inpaintFullResPadding?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    inpaintingMaskInvert?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingImg2Img
     */
    initialNoiseMultiplier?: number;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingImg2Img
     */
    latentMask?: string;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingImg2Img
     */
    samplerIndex?: string;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingImg2Img
     */
    includeInitImages?: boolean;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingImg2Img
     */
    scriptName?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof StableDiffusionProcessingImg2Img
     */
    scriptArgs?: Array<any>;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingImg2Img
     */
    sendImages?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingImg2Img
     */
    saveImages?: boolean;
    /**
     * 
     * @type {object}
     * @memberof StableDiffusionProcessingImg2Img
     */
    alwaysonScripts?: object;
}

/**
 * Check if a given object implements the StableDiffusionProcessingImg2Img interface.
 */
export function instanceOfStableDiffusionProcessingImg2Img(value: object): value is StableDiffusionProcessingImg2Img {
    return true;
}

export function StableDiffusionProcessingImg2ImgFromJSON(json: any): StableDiffusionProcessingImg2Img {
    return StableDiffusionProcessingImg2ImgFromJSONTyped(json, false);
}

export function StableDiffusionProcessingImg2ImgFromJSONTyped(json: any, ignoreDiscriminator: boolean): StableDiffusionProcessingImg2Img {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'negativePrompt': json['negative_prompt'] == null ? undefined : json['negative_prompt'],
        'styles': json['styles'] == null ? undefined : json['styles'],
        'seed': json['seed'] == null ? undefined : json['seed'],
        'subseed': json['subseed'] == null ? undefined : json['subseed'],
        'subseedStrength': json['subseed_strength'] == null ? undefined : json['subseed_strength'],
        'seedResizeFromH': json['seed_resize_from_h'] == null ? undefined : json['seed_resize_from_h'],
        'seedResizeFromW': json['seed_resize_from_w'] == null ? undefined : json['seed_resize_from_w'],
        'samplerName': json['sampler_name'] == null ? undefined : json['sampler_name'],
        'batchSize': json['batch_size'] == null ? undefined : json['batch_size'],
        'nIter': json['n_iter'] == null ? undefined : json['n_iter'],
        'steps': json['steps'] == null ? undefined : json['steps'],
        'cfgScale': json['cfg_scale'] == null ? undefined : json['cfg_scale'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'restoreFaces': json['restore_faces'] == null ? undefined : json['restore_faces'],
        'tiling': json['tiling'] == null ? undefined : json['tiling'],
        'doNotSaveSamples': json['do_not_save_samples'] == null ? undefined : json['do_not_save_samples'],
        'doNotSaveGrid': json['do_not_save_grid'] == null ? undefined : json['do_not_save_grid'],
        'eta': json['eta'] == null ? undefined : json['eta'],
        'denoisingStrength': json['denoising_strength'] == null ? undefined : json['denoising_strength'],
        'sMinUncond': json['s_min_uncond'] == null ? undefined : json['s_min_uncond'],
        'sChurn': json['s_churn'] == null ? undefined : json['s_churn'],
        'sTmax': json['s_tmax'] == null ? undefined : json['s_tmax'],
        'sTmin': json['s_tmin'] == null ? undefined : json['s_tmin'],
        'sNoise': json['s_noise'] == null ? undefined : json['s_noise'],
        'overrideSettings': json['override_settings'] == null ? undefined : json['override_settings'],
        'overrideSettingsRestoreAfterwards': json['override_settings_restore_afterwards'] == null ? undefined : json['override_settings_restore_afterwards'],
        'refinerCheckpoint': json['refiner_checkpoint'] == null ? undefined : json['refiner_checkpoint'],
        'refinerSwitchAt': json['refiner_switch_at'] == null ? undefined : json['refiner_switch_at'],
        'disableExtraNetworks': json['disable_extra_networks'] == null ? undefined : json['disable_extra_networks'],
        'comments': json['comments'] == null ? undefined : json['comments'],
        'initImages': json['init_images'] == null ? undefined : json['init_images'],
        'resizeMode': json['resize_mode'] == null ? undefined : json['resize_mode'],
        'imageCfgScale': json['image_cfg_scale'] == null ? undefined : json['image_cfg_scale'],
        'mask': json['mask'] == null ? undefined : json['mask'],
        'maskBlurX': json['mask_blur_x'] == null ? undefined : json['mask_blur_x'],
        'maskBlurY': json['mask_blur_y'] == null ? undefined : json['mask_blur_y'],
        'maskBlur': json['mask_blur'] == null ? undefined : json['mask_blur'],
        'inpaintingFill': json['inpainting_fill'] == null ? undefined : json['inpainting_fill'],
        'inpaintFullRes': json['inpaint_full_res'] == null ? undefined : json['inpaint_full_res'],
        'inpaintFullResPadding': json['inpaint_full_res_padding'] == null ? undefined : json['inpaint_full_res_padding'],
        'inpaintingMaskInvert': json['inpainting_mask_invert'] == null ? undefined : json['inpainting_mask_invert'],
        'initialNoiseMultiplier': json['initial_noise_multiplier'] == null ? undefined : json['initial_noise_multiplier'],
        'latentMask': json['latent_mask'] == null ? undefined : json['latent_mask'],
        'samplerIndex': json['sampler_index'] == null ? undefined : json['sampler_index'],
        'includeInitImages': json['include_init_images'] == null ? undefined : json['include_init_images'],
        'scriptName': json['script_name'] == null ? undefined : json['script_name'],
        'scriptArgs': json['script_args'] == null ? undefined : json['script_args'],
        'sendImages': json['send_images'] == null ? undefined : json['send_images'],
        'saveImages': json['save_images'] == null ? undefined : json['save_images'],
        'alwaysonScripts': json['alwayson_scripts'] == null ? undefined : json['alwayson_scripts'],
    };
}

  export function StableDiffusionProcessingImg2ImgToJSON(json: any): StableDiffusionProcessingImg2Img {
      return StableDiffusionProcessingImg2ImgToJSONTyped(json, false);
  }

  export function StableDiffusionProcessingImg2ImgToJSONTyped(value?: StableDiffusionProcessingImg2Img | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'negative_prompt': value['negativePrompt'],
        'styles': value['styles'],
        'seed': value['seed'],
        'subseed': value['subseed'],
        'subseed_strength': value['subseedStrength'],
        'seed_resize_from_h': value['seedResizeFromH'],
        'seed_resize_from_w': value['seedResizeFromW'],
        'sampler_name': value['samplerName'],
        'batch_size': value['batchSize'],
        'n_iter': value['nIter'],
        'steps': value['steps'],
        'cfg_scale': value['cfgScale'],
        'width': value['width'],
        'height': value['height'],
        'restore_faces': value['restoreFaces'],
        'tiling': value['tiling'],
        'do_not_save_samples': value['doNotSaveSamples'],
        'do_not_save_grid': value['doNotSaveGrid'],
        'eta': value['eta'],
        'denoising_strength': value['denoisingStrength'],
        's_min_uncond': value['sMinUncond'],
        's_churn': value['sChurn'],
        's_tmax': value['sTmax'],
        's_tmin': value['sTmin'],
        's_noise': value['sNoise'],
        'override_settings': value['overrideSettings'],
        'override_settings_restore_afterwards': value['overrideSettingsRestoreAfterwards'],
        'refiner_checkpoint': value['refinerCheckpoint'],
        'refiner_switch_at': value['refinerSwitchAt'],
        'disable_extra_networks': value['disableExtraNetworks'],
        'comments': value['comments'],
        'init_images': value['initImages'],
        'resize_mode': value['resizeMode'],
        'image_cfg_scale': value['imageCfgScale'],
        'mask': value['mask'],
        'mask_blur_x': value['maskBlurX'],
        'mask_blur_y': value['maskBlurY'],
        'mask_blur': value['maskBlur'],
        'inpainting_fill': value['inpaintingFill'],
        'inpaint_full_res': value['inpaintFullRes'],
        'inpaint_full_res_padding': value['inpaintFullResPadding'],
        'inpainting_mask_invert': value['inpaintingMaskInvert'],
        'initial_noise_multiplier': value['initialNoiseMultiplier'],
        'latent_mask': value['latentMask'],
        'sampler_index': value['samplerIndex'],
        'include_init_images': value['includeInitImages'],
        'script_name': value['scriptName'],
        'script_args': value['scriptArgs'],
        'send_images': value['sendImages'],
        'save_images': value['saveImages'],
        'alwayson_scripts': value['alwaysonScripts'],
    };
}

