/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StableDiffusionProcessingTxt2Img
 */
export interface StableDiffusionProcessingTxt2Img {
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    prompt?: string;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    negativePrompt?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    styles?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    seed?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    subseed?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    subseedStrength?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    seedResizeFromH?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    seedResizeFromW?: number;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    samplerName?: string;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    batchSize?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    nIter?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    steps?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    cfgScale?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    height?: number;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    restoreFaces?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    tiling?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    doNotSaveSamples?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    doNotSaveGrid?: boolean;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    eta?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    denoisingStrength?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    sMinUncond?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    sChurn?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    sTmax?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    sTmin?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    sNoise?: number;
    /**
     * 
     * @type {object}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    overrideSettings?: object;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    overrideSettingsRestoreAfterwards?: boolean;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    refinerCheckpoint?: string;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    refinerSwitchAt?: number;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    disableExtraNetworks?: boolean;
    /**
     * 
     * @type {object}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    comments?: object;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    enableHr?: boolean;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    firstphaseWidth?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    firstphaseHeight?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrScale?: number;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrUpscaler?: string;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrSecondPassSteps?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrResizeX?: number;
    /**
     * 
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrResizeY?: number;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrCheckpointName?: string;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrSamplerName?: string;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrPrompt?: string;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrNegativePrompt?: string;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    samplerIndex?: string;
    /**
     * 
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    scriptName?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    scriptArgs?: Array<any>;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    sendImages?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    saveImages?: boolean;
    /**
     * 
     * @type {object}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    alwaysonScripts?: object;
}

/**
 * Check if a given object implements the StableDiffusionProcessingTxt2Img interface.
 */
export function instanceOfStableDiffusionProcessingTxt2Img(value: object): value is StableDiffusionProcessingTxt2Img {
    return true;
}

export function StableDiffusionProcessingTxt2ImgFromJSON(json: any): StableDiffusionProcessingTxt2Img {
    return StableDiffusionProcessingTxt2ImgFromJSONTyped(json, false);
}

export function StableDiffusionProcessingTxt2ImgFromJSONTyped(json: any, ignoreDiscriminator: boolean): StableDiffusionProcessingTxt2Img {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'negativePrompt': json['negative_prompt'] == null ? undefined : json['negative_prompt'],
        'styles': json['styles'] == null ? undefined : json['styles'],
        'seed': json['seed'] == null ? undefined : json['seed'],
        'subseed': json['subseed'] == null ? undefined : json['subseed'],
        'subseedStrength': json['subseed_strength'] == null ? undefined : json['subseed_strength'],
        'seedResizeFromH': json['seed_resize_from_h'] == null ? undefined : json['seed_resize_from_h'],
        'seedResizeFromW': json['seed_resize_from_w'] == null ? undefined : json['seed_resize_from_w'],
        'samplerName': json['sampler_name'] == null ? undefined : json['sampler_name'],
        'batchSize': json['batch_size'] == null ? undefined : json['batch_size'],
        'nIter': json['n_iter'] == null ? undefined : json['n_iter'],
        'steps': json['steps'] == null ? undefined : json['steps'],
        'cfgScale': json['cfg_scale'] == null ? undefined : json['cfg_scale'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'restoreFaces': json['restore_faces'] == null ? undefined : json['restore_faces'],
        'tiling': json['tiling'] == null ? undefined : json['tiling'],
        'doNotSaveSamples': json['do_not_save_samples'] == null ? undefined : json['do_not_save_samples'],
        'doNotSaveGrid': json['do_not_save_grid'] == null ? undefined : json['do_not_save_grid'],
        'eta': json['eta'] == null ? undefined : json['eta'],
        'denoisingStrength': json['denoising_strength'] == null ? undefined : json['denoising_strength'],
        'sMinUncond': json['s_min_uncond'] == null ? undefined : json['s_min_uncond'],
        'sChurn': json['s_churn'] == null ? undefined : json['s_churn'],
        'sTmax': json['s_tmax'] == null ? undefined : json['s_tmax'],
        'sTmin': json['s_tmin'] == null ? undefined : json['s_tmin'],
        'sNoise': json['s_noise'] == null ? undefined : json['s_noise'],
        'overrideSettings': json['override_settings'] == null ? undefined : json['override_settings'],
        'overrideSettingsRestoreAfterwards': json['override_settings_restore_afterwards'] == null ? undefined : json['override_settings_restore_afterwards'],
        'refinerCheckpoint': json['refiner_checkpoint'] == null ? undefined : json['refiner_checkpoint'],
        'refinerSwitchAt': json['refiner_switch_at'] == null ? undefined : json['refiner_switch_at'],
        'disableExtraNetworks': json['disable_extra_networks'] == null ? undefined : json['disable_extra_networks'],
        'comments': json['comments'] == null ? undefined : json['comments'],
        'enableHr': json['enable_hr'] == null ? undefined : json['enable_hr'],
        'firstphaseWidth': json['firstphase_width'] == null ? undefined : json['firstphase_width'],
        'firstphaseHeight': json['firstphase_height'] == null ? undefined : json['firstphase_height'],
        'hrScale': json['hr_scale'] == null ? undefined : json['hr_scale'],
        'hrUpscaler': json['hr_upscaler'] == null ? undefined : json['hr_upscaler'],
        'hrSecondPassSteps': json['hr_second_pass_steps'] == null ? undefined : json['hr_second_pass_steps'],
        'hrResizeX': json['hr_resize_x'] == null ? undefined : json['hr_resize_x'],
        'hrResizeY': json['hr_resize_y'] == null ? undefined : json['hr_resize_y'],
        'hrCheckpointName': json['hr_checkpoint_name'] == null ? undefined : json['hr_checkpoint_name'],
        'hrSamplerName': json['hr_sampler_name'] == null ? undefined : json['hr_sampler_name'],
        'hrPrompt': json['hr_prompt'] == null ? undefined : json['hr_prompt'],
        'hrNegativePrompt': json['hr_negative_prompt'] == null ? undefined : json['hr_negative_prompt'],
        'samplerIndex': json['sampler_index'] == null ? undefined : json['sampler_index'],
        'scriptName': json['script_name'] == null ? undefined : json['script_name'],
        'scriptArgs': json['script_args'] == null ? undefined : json['script_args'],
        'sendImages': json['send_images'] == null ? undefined : json['send_images'],
        'saveImages': json['save_images'] == null ? undefined : json['save_images'],
        'alwaysonScripts': json['alwayson_scripts'] == null ? undefined : json['alwayson_scripts'],
    };
}

  export function StableDiffusionProcessingTxt2ImgToJSON(json: any): StableDiffusionProcessingTxt2Img {
      return StableDiffusionProcessingTxt2ImgToJSONTyped(json, false);
  }

  export function StableDiffusionProcessingTxt2ImgToJSONTyped(value?: StableDiffusionProcessingTxt2Img | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'negative_prompt': value['negativePrompt'],
        'styles': value['styles'],
        'seed': value['seed'],
        'subseed': value['subseed'],
        'subseed_strength': value['subseedStrength'],
        'seed_resize_from_h': value['seedResizeFromH'],
        'seed_resize_from_w': value['seedResizeFromW'],
        'sampler_name': value['samplerName'],
        'batch_size': value['batchSize'],
        'n_iter': value['nIter'],
        'steps': value['steps'],
        'cfg_scale': value['cfgScale'],
        'width': value['width'],
        'height': value['height'],
        'restore_faces': value['restoreFaces'],
        'tiling': value['tiling'],
        'do_not_save_samples': value['doNotSaveSamples'],
        'do_not_save_grid': value['doNotSaveGrid'],
        'eta': value['eta'],
        'denoising_strength': value['denoisingStrength'],
        's_min_uncond': value['sMinUncond'],
        's_churn': value['sChurn'],
        's_tmax': value['sTmax'],
        's_tmin': value['sTmin'],
        's_noise': value['sNoise'],
        'override_settings': value['overrideSettings'],
        'override_settings_restore_afterwards': value['overrideSettingsRestoreAfterwards'],
        'refiner_checkpoint': value['refinerCheckpoint'],
        'refiner_switch_at': value['refinerSwitchAt'],
        'disable_extra_networks': value['disableExtraNetworks'],
        'comments': value['comments'],
        'enable_hr': value['enableHr'],
        'firstphase_width': value['firstphaseWidth'],
        'firstphase_height': value['firstphaseHeight'],
        'hr_scale': value['hrScale'],
        'hr_upscaler': value['hrUpscaler'],
        'hr_second_pass_steps': value['hrSecondPassSteps'],
        'hr_resize_x': value['hrResizeX'],
        'hr_resize_y': value['hrResizeY'],
        'hr_checkpoint_name': value['hrCheckpointName'],
        'hr_sampler_name': value['hrSamplerName'],
        'hr_prompt': value['hrPrompt'],
        'hr_negative_prompt': value['hrNegativePrompt'],
        'sampler_index': value['samplerIndex'],
        'script_name': value['scriptName'],
        'script_args': value['scriptArgs'],
        'send_images': value['sendImages'],
        'save_images': value['saveImages'],
        'alwayson_scripts': value['alwaysonScripts'],
    };
}

