/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpscalerItem
 */
export interface UpscalerItem {
    /**
     * 
     * @type {string}
     * @memberof UpscalerItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpscalerItem
     */
    modelName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpscalerItem
     */
    modelPath?: string;
    /**
     * 
     * @type {string}
     * @memberof UpscalerItem
     */
    modelUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof UpscalerItem
     */
    scale?: number;
}

/**
 * Check if a given object implements the UpscalerItem interface.
 */
export function instanceOfUpscalerItem(value: object): value is UpscalerItem {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpscalerItemFromJSON(json: any): UpscalerItem {
    return UpscalerItemFromJSONTyped(json, false);
}

export function UpscalerItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpscalerItem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'modelName': json['model_name'] == null ? undefined : json['model_name'],
        'modelPath': json['model_path'] == null ? undefined : json['model_path'],
        'modelUrl': json['model_url'] == null ? undefined : json['model_url'],
        'scale': json['scale'] == null ? undefined : json['scale'],
    };
}

  export function UpscalerItemToJSON(json: any): UpscalerItem {
      return UpscalerItemToJSONTyped(json, false);
  }

  export function UpscalerItemToJSONTyped(value?: UpscalerItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'model_name': value['modelName'],
        'model_path': value['modelPath'],
        'model_url': value['modelUrl'],
        'scale': value['scale'],
    };
}

